// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuqogpswsdzlxuaeidcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cW9ncHN3c2R6bHh1YWVpZGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5MjE3OTQsImV4cCI6MjA5ODQ5Nzc5NH0.Ay7HzlmDixWDGfFfrE2oOYaocSpR0qNpL3D9x4KJa24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser =
  typeof globalThis !== "undefined" &&
  typeof (globalThis as { window?: unknown }).window !== "undefined" &&
  typeof (globalThis as { document?: unknown }).document !== "undefined";

const browserStorage = (() => {
  if (!isBrowser) return undefined;
  try {
    return (globalThis as unknown as { localStorage?: Storage }).localStorage;
  } catch {
    return undefined;
  }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserStorage,
    persistSession: isBrowser && !!browserStorage,
    autoRefreshToken: isBrowser,
  }
});